import { useEffect, useState } from 'react';
import {
  PageHeader, SectionCard, StatCard, Badge,
  LoadingState, ErrorState, FlagDonut, CategoryBar,
  AmendmentCreepLine, ScatterAnomaly, useTheme,
  VIZ,
} from '../../ui-kit';
import { api } from '../lib/api';

const BUCKET_TONE = {
  overhead_extraction: 'red',
  receipt_generation:  'red',
  revenue_inflation:   'yellow',
  structural:          'gray',
  low_risk:            'green',
};

const BUCKET_COLOR = {
  overhead_extraction: '#EF4444',
  receipt_generation:  '#B91C1C',
  revenue_inflation:   '#F59E0B',
  structural:          '#71717A',
  low_risk:            '#10B981',
};

const fmtPct = (n) => `${(n * 100).toFixed(1)}%`;
const fmtMoneyShort = (n) => {
  if (n == null) return '$0';
  if (n >= 1_000_000_000) return `$${(n / 1_000_000_000).toFixed(2)}B`;
  if (n >= 1_000_000) return `$${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `$${(n / 1_000).toFixed(0)}K`;
  return `$${n.toFixed(0)}`;
};

export default function Summary() {
  const { C } = useTheme();
  const [data, setData] = useState(null);
  const [err, setErr]   = useState(null);
  const [narrative, setNarrative] = useState(null);
  const [narrErr, setNarrErr] = useState(null);
  const [narrLoading, setNarrLoading] = useState(false);

  useEffect(() => {
    api.summary().then(setData).catch(e => setErr(e.message));
  }, []);

  useEffect(() => {
    if (!data) return;
    setNarrLoading(true);
    api.summaryNarrative()
      .then(setNarrative)
      .catch(e => setNarrErr(e.message))
      .finally(() => setNarrLoading(false));
  }, [data]);

  if (err)   return <ErrorState message={err} />;
  if (!data) return <LoadingState message="Loading summary…" />;

  const donutData = Object.entries(data.buckets)
    .filter(([, b]) => b.count > 0)
    .map(([key, b]) => ({
      name: b.label,
      value: Math.round(b.total_flow),
      color: BUCKET_COLOR[key],
      key,
    }));

  const topLoopsBar = (data.top_loops || []).map(l => ({
    label: truncate(l.short_label, 32),
    value: l.total_flow,
    worst: l.worst,
  }));

  const hopBar = (data.hop_distribution || []).map(h => ({
    label: h.label,
    value: h.flow,
    count: h.count,
  }));

  const tierBar = (data.tier_distribution || []).map(t => ({
    label: String(t.tier).toUpperCase(),
    value: t.flow,
    count: t.count,
  }));

  const yearLine = (data.year_distribution || []).map(y => ({
    year: y.year,
    value: y.flow,
  }));

  const scatterData = (data.scatter || []).map(s => ({
    ...s,
    color: BUCKET_COLOR[s.worst] ?? VIZ.alert,
  }));

  return (
    <div>
      <PageHeader
        section="OVERVIEW"
        title="Findings Summary"
        subtitle="Aggregate analysis across all qualifying loops, bucketed by classification."
        accent={C.purple}
      />

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 14, marginBottom: 22 }}>
        <StatCard label="Loops Analyzed"       value={String(data.total_loops_analyzed)} />
        <StatCard label="Total Flow"           value={data.total_flow_fmt} accent={C.purple} />
        <StatCard label="Median Flow / Loop"   value={data.median_flow_fmt} sub={`avg ${data.avg_flow_per_loop_fmt}`} />
        <StatCard
          label="Top-10 Concentration"
          value={fmtPct(data.concentration_top10)}
          sub={`top-5: ${fmtPct(data.concentration_top5)}`}
          accent={C.warning}
        />
      </div>

      {/* Narrative */}
      <div style={{ marginBottom: 22 }}>
        <SectionCard
          title="Executive Narrative"
          subtitle={narrative?.model ? `Generated by ${narrative.model}` : 'AI-synthesized findings'}
          accent={C.purple}
        >
          {narrLoading && !narrative && (
            <div style={{ color: C.text3, fontSize: 12 }}>Synthesizing narrative…</div>
          )}
          {narrErr && (
            <div style={{ color: C.danger, fontSize: 12 }}>{narrErr}</div>
          )}
          {narrative && (
            <div style={{ fontSize: 13, color: C.text2, lineHeight: 1.65, whiteSpace: 'pre-wrap' }}>
              {narrative.narrative}
            </div>
          )}
        </SectionCard>
      </div>

      {/* Row 1: Donut + Top loops */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1.4fr', gap: 18, alignItems: 'start', marginBottom: 18 }}>
        <SectionCard title="Flow by Classification" subtitle="Share of total dollars per risk bucket">
          {donutData.length ? (
            <FlagDonut data={donutData} height={280} innerLabel={() => fmtMoneyShort(data.total_flow)} />
          ) : (
            <div style={{ color: C.text3, fontSize: 12 }}>No data.</div>
          )}
        </SectionCard>

        <SectionCard title="Top 10 Loops by Flow" subtitle="Largest dollar cycles in the dataset">
          {topLoopsBar.length ? (
            <CategoryBar
              data={topLoopsBar}
              orientation="horizontal"
              height={320}
              tickFormatter={fmtMoneyShort}
              tooltipFmt={(v, _n, p) => `${p.payload.label}\n${fmtMoneyShort(v)}`}
              yAxisWidth={210}
              color={C.purple}
            />
          ) : (
            <div style={{ color: C.text3, fontSize: 12 }}>No data.</div>
          )}
        </SectionCard>
      </div>

      {/* Row 2: Hop + Tier distribution */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 18, alignItems: 'start', marginBottom: 18 }}>
        <SectionCard title="Loops by Hop Length" subtitle="Cycle complexity (more hops = harder to detect)">
          {hopBar.length ? (
            <CategoryBar
              data={hopBar}
              orientation="vertical"
              height={240}
              tickFormatter={fmtMoneyShort}
              tooltipFmt={(v, _n, p) => `${p.payload.label}\n${p.payload.count} loops · ${fmtMoneyShort(v)}`}
              color={C.cyan}
            />
          ) : (
            <div style={{ color: C.text3, fontSize: 12 }}>No data.</div>
          )}
        </SectionCard>

        <SectionCard title="Loops by Risk Tier" subtitle="Pre-scored severity (P50…P99)">
          {tierBar.length ? (
            <CategoryBar
              data={tierBar}
              orientation="vertical"
              height={240}
              tickFormatter={fmtMoneyShort}
              tooltipFmt={(v, _n, p) => `${p.payload.label}\n${p.payload.count} loops · ${fmtMoneyShort(v)}`}
              color={C.warning}
            />
          ) : (
            <div style={{ color: C.text3, fontSize: 12 }}>No data.</div>
          )}
        </SectionCard>
      </div>

      {/* Row 3: Year activity + Scatter */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 18, alignItems: 'start', marginBottom: 18 }}>
        <SectionCard title="Loop Activity Over Time" subtitle="Estimated flow attributed by year (linear span split)">
          {yearLine.length ? (
            <AmendmentCreepLine
              data={yearLine}
              xKey="year"
              yKey="value"
              tickFormatter={fmtMoneyShort}
              height={240}
              alertGrowth={3}
            />
          ) : (
            <div style={{ color: C.text3, fontSize: 12 }}>No data.</div>
          )}
        </SectionCard>

        <SectionCard title="Loop Size vs. Complexity" subtitle="Bubble size = hop count · color = worst classification">
          {scatterData.length ? (
            <ScatterAnomaly
              data={scatterData}
              xKey="x" yKey="y" zKey="z"
              xLabel="Unique orgs in loop"
              yLabel="Total flow"
              yTickFormatter={fmtMoneyShort}
              height={240}
              tooltip={(d) => (
                <div style={{ color: '#fff', fontSize: 12, lineHeight: 1.5 }}>
                  <div style={{ fontWeight: 600, marginBottom: 4 }}>{d.name}</div>
                  <div>{d.x} orgs · {Math.round(d.z / 40)} hops</div>
                  <div style={{ color: '#FCD34D' }}>{d.flow_fmt}</div>
                </div>
              )}
            />
          ) : (
            <div style={{ color: C.text3, fontSize: 12 }}>No data.</div>
          )}
        </SectionCard>
      </div>

      {/* Buckets detail */}
      <SectionCard title="Bucket Detail" subtitle="Breakdown by classification with sample loops">
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: 12 }}>
          {Object.entries(data.buckets).map(([key, b]) => (
            <div key={key} style={{
              padding: 14, borderRadius: 8,
              background: C.surface2, border: `1px solid ${C.border}`,
              borderLeft: `3px solid ${BUCKET_COLOR[key]}`,
            }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 }}>
                <Badge color={BUCKET_TONE[key] ?? 'gray'}>{b.label}</Badge>
                <span style={{
                  fontFamily: 'var(--font-geist-mono), monospace',
                  fontSize: 13, fontWeight: 700, color: C.text,
                }}>{b.total_flow_fmt}</span>
              </div>
              <div style={{
                display: 'flex', justifyContent: 'space-between',
                fontSize: 11, color: C.text3, marginBottom: 10,
                fontFamily: 'var(--font-geist-mono), monospace',
              }}>
                <span>{b.count} loops</span>
                <span>avg {b.avg_flow_fmt}</span>
                <span>{fmtPct(b.share_of_total)} of total</span>
              </div>
              {b.top_loops.slice(0, 3).map(l => (
                <div key={l.id} style={{
                  fontSize: 11, color: C.text2, padding: '3px 0',
                  display: 'flex', justifyContent: 'space-between', gap: 8,
                }}>
                  <span style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                    {l.short_label}
                  </span>
                  <span style={{ fontFamily: 'var(--font-geist-mono), monospace', color: C.text3, flexShrink: 0 }}>
                    {l.total_flow_fmt}
                  </span>
                </div>
              ))}
            </div>
          ))}
        </div>
      </SectionCard>
    </div>
  );
}

function truncate(s, n) {
  if (!s) return s;
  return s.length > n ? s.slice(0, n - 1) + '…' : s;
}
