import { useEffect, useState } from 'react';
import {
  PageHeader, SectionCard, StatCard, Badge,
  LoadingState, ErrorState, FlagDonut, CategoryBar,
  AmendmentCreepLine, ScatterAnomaly, useTheme,
  VIZ,
} from '../../ui-kit';
import { api } from '../lib/api';

const BUCKET_TONE = {
  overhead_extraction: 'red',
  receipt_generation:  'red',
  revenue_inflation:   'yellow',
  structural:          'gray',
  low_risk:            'green',
};

const BUCKET_COLOR = {
  overhead_extraction: '#EF4444',
  receipt_generation:  '#B91C1C',
  revenue_inflation:   '#F59E0B',
  structural:          '#71717A',
  low_risk:            '#10B981',
};

const fmtPct = (n) => `${(n * 100).toFixed(1)}%`;
const fmtMoneyShort = (n) => {
  if (n == null) return '$0';
  if (n >= 1_000_000_000) return `$${(n / 1_000_000_000).toFixed(2)}B`;
  if (n >= 1_000_000) return `$${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `$${(n / 1_000).toFixed(0)}K`;
  return `$${n.toFixed(0)}`;
};

export default function Summary() {
  const { C } = useTheme();
  const [data, setData] = useState(null);
  const [err, setErr]   = useState(null);
  const [narrative, setNarrative] = useState(null);
  const [narrErr, setNarrErr] = useState(null);
  const [narrLoading, setNarrLoading] = useState(false);

  useEffect(() => {
    api.summary().then(setData).catch(e => setErr(e.message));
    setNarrLoading(true);
    api.summaryNarrative()
      .then(setNarrative)
      .catch(e => setNarrErr(e.message))
      .finally(() => setNarrLoading(false));
  }, []);

  if (err)   return <ErrorState message={err} />;
  if (!data) return <LoadingState message="Loading summary…" />;

  const donutData = Object.entries(data.buckets)
    .filter(([, b]) => b.count > 0)
    .map(([key, b]) => ({
      name: b.label,
      value: Math.round(b.total_flow),
      color: BUCKET_COLOR[key],
      key,
    }));

  const topLoopsBar = (data.top_loops || []).map(l => ({
    label: truncate(l.short_label, 32),
    value: l.total_flow,
    worst: l.worst,
  }));

  const hopBar = (data.hop_distribution || []).map(h => ({
    label: h.label,
    value: h.flow,
    count: h.count,
  }));

  const tierBar = (data.tier_distribution || []).map(t => ({
    label: String(t.tier).toUpperCase(),
    value: t.flow,
    count: t.count,
  }));

  const yearLine = (data.year_distribution || []).map(y => ({
    year: y.year,
    value: y.flow,
  }));

  const scatterData = (data.scatter || []).map(s => ({
    ...s,
    color: BUCKET_COLOR[s.worst] ?? VIZ.alert,
  }));

  return (
    <div>
      <PageHeader
        section="OVERVIEW"
        title="Findings Summary"
        subtitle="Aggregate analysis across all qualifying loops, bucketed by classification."
        accent={C.purple}
      />

      <div className="grid grid-cols-4 gap-3.5 mb-[22px]">
        <StatCard label="Loops Analyzed"       value={String(data.total_loops_analyzed)} />
        <StatCard label="Total Flow"           value={data.total_flow_fmt} accent={C.purple} />
        <StatCard label="Median Flow / Loop"   value={data.median_flow_fmt} sub={`avg ${data.avg_flow_per_loop_fmt}`} />
        <StatCard
          label="Top-10 Concentration"
          value={fmtPct(data.concentration_top10)}
          sub={`top-5: ${fmtPct(data.concentration_top5)}`}
          accent={C.warning}
        />
      </div>

      <div className="mb-[22px]">
        <SectionCard
          title="Executive Narrative"
          subtitle={narrative?.model ? `Generated by ${narrative.model}` : 'AI-synthesized findings'}
          accent={C.purple}
        >
          {narrLoading && !narrative && (
            <div className="text-text3 text-[12px]">Synthesizing narrative…</div>
          )}
          {narrErr && (
            <div className="text-danger text-[12px]">{narrErr}</div>
          )}
          {narrative && (
            <div
              className="text-[13px] text-text2 whitespace-pre-wrap"
              style={{ lineHeight: 1.65 }}
            >
              {narrative.narrative}
            </div>
          )}
        </SectionCard>
      </div>

      <div
        className="grid gap-[18px] items-start mb-[18px]"
        style={{ gridTemplateColumns: '1fr 1.4fr' }}
      >
        <SectionCard title="Flow by Classification" subtitle="Share of total dollars per risk bucket">
          {donutData.length ? (
            <FlagDonut data={donutData} height={280} innerLabel={() => fmtMoneyShort(data.total_flow)} />
          ) : (
            <div className="text-text3 text-[12px]">No data.</div>
          )}
        </SectionCard>

        <SectionCard title="Top 10 Loops by Flow" subtitle="Largest dollar cycles in the dataset">
          {topLoopsBar.length ? (
            <CategoryBar
              data={topLoopsBar}
              orientation="horizontal"
              height={320}
              tickFormatter={fmtMoneyShort}
              tooltipFmt={(v, _n, p) => `${p.payload.label}\n${fmtMoneyShort(v)}`}
              yAxisWidth={210}
              color={C.purple}
            />
          ) : (
            <div className="text-text3 text-[12px]">No data.</div>
          )}
        </SectionCard>
      </div>

      <div className="grid grid-cols-2 gap-[18px] items-start mb-[18px]">
        <SectionCard title="Loops by Hop Length" subtitle="Cycle complexity (more hops = harder to detect)">
          {hopBar.length ? (
            <CategoryBar
              data={hopBar}
              orientation="vertical"
              height={240}
              tickFormatter={fmtMoneyShort}
              tooltipFmt={(v, _n, p) => `${p.payload.label}\n${p.payload.count} loops · ${fmtMoneyShort(v)}`}
              color={C.cyan}
            />
          ) : (
            <div className="text-text3 text-[12px]">No data.</div>
          )}
        </SectionCard>

        <SectionCard title="Loops by Risk Tier" subtitle="Pre-scored severity (P50…P99)">
          {tierBar.length ? (
            <CategoryBar
              data={tierBar}
              orientation="vertical"
              height={240}
              tickFormatter={fmtMoneyShort}
              tooltipFmt={(v, _n, p) => `${p.payload.label}\n${p.payload.count} loops · ${fmtMoneyShort(v)}`}
              color={C.warning}
            />
          ) : (
            <div className="text-text3 text-[12px]">No data.</div>
          )}
        </SectionCard>
      </div>

      <div className="grid grid-cols-2 gap-[18px] items-start mb-[18px]">
        <SectionCard title="Loop Activity Over Time" subtitle="Estimated flow attributed by year (linear span split)">
          {yearLine.length ? (
            <AmendmentCreepLine
              data={yearLine}
              xKey="year"
              yKey="value"
              tickFormatter={fmtMoneyShort}
              height={240}
              alertGrowth={3}
            />
          ) : (
            <div className="text-text3 text-[12px]">No data.</div>
          )}
        </SectionCard>

        <SectionCard title="Loop Size vs. Complexity" subtitle="Bubble size = hop count · color = worst classification">
          {scatterData.length ? (
            <ScatterAnomaly
              data={scatterData}
              xKey="x" yKey="y" zKey="z"
              xLabel="Unique orgs in loop"
              yLabel="Total flow"
              yTickFormatter={fmtMoneyShort}
              height={240}
              tooltip={(d) => (
                <div style={{ color: '#fff', fontSize: 12, lineHeight: 1.5 }}>
                  <div style={{ fontWeight: 600, marginBottom: 4 }}>{d.name}</div>
                  <div>{d.x} orgs · {Math.round(d.z / 40)} hops</div>
                  <div style={{ color: '#FCD34D' }}>{d.flow_fmt}</div>
                </div>
              )}
            />
          ) : (
            <div className="text-text3 text-[12px]">No data.</div>
          )}
        </SectionCard>
      </div>

      <SectionCard title="Bucket Detail" subtitle="Breakdown by classification with sample loops">
        <div className="grid grid-cols-2 gap-3">
          {Object.entries(data.buckets).map(([key, b]) => (
            <div
              key={key}
              className="p-3.5 rounded-lg bg-surface2 border border-border"
              style={{ borderLeft: `3px solid ${BUCKET_COLOR[key]}` }}
            >
              <div className="flex justify-between items-center mb-2">
                <Badge color={BUCKET_TONE[key] ?? 'gray'}>{b.label}</Badge>
                <span className="font-mono text-[13px] font-bold text-text">
                  {b.total_flow_fmt}
                </span>
              </div>
              <div className="flex justify-between text-[11px] text-text3 mb-2.5 font-mono">
                <span>{b.count} loops</span>
                <span>avg {b.avg_flow_fmt}</span>
                <span>{fmtPct(b.share_of_total)} of total</span>
              </div>
              {b.top_loops.slice(0, 3).map(l => (
                <div
                  key={l.id}
                  className="text-[11px] text-text2 py-0.5 flex justify-between gap-2"
                >
                  <span className="truncate">{l.short_label}</span>
                  <span className="font-mono text-text3 shrink-0">
                    {l.total_flow_fmt}
                  </span>
                </div>
              ))}
            </div>
          ))}
        </div>
      </SectionCard>
    </div>
  );
}

function truncate(s, n) {
  if (!s) return s;
  return s.length > n ? s.slice(0, n - 1) + '…' : s;
}
